# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: nginx:latest

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

configmap:
  nginx: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie_service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast_service:8000/api/v1/casts;
      }
    }

autoscaling:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
