# Default values for movie.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: p0l1na/jenkins_fastapi_casts
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8002
  targetPort: 8000

env:
  database_uri: cG9zdGdyZXNxbDovL2Nhc3RfZGJfdXNlcm5hbWU6Y2FzdF9kYl9wYXNzd29yZEBjYXN0X2RiL2Nhc3RfZGJfZGV2Cg==
